// <auto-generated />
using System;
using Dt191G_moment3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dt191Gmoment3.Migrations.Borrow
{
    [DbContext(typeof(BorrowContext))]
    [Migration("20230214123119_UpdateBorrowTableAlbumId")]
    partial class UpdateBorrowTableAlbumId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Dt191G_moment3.Models.Borrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BorrowedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowedTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Borrow");
                });
#pragma warning restore 612, 618
        }
    }
}
